apiVersion: v1
kind: Service
metadata:
    name: adidas-test
    namespace: pro
spec:
    type: LoadBalancer
    ports:
        -
            port: 80
            targetPort: 8080
    selector:
        app: adidas-test